### ISSUE TITLE
this will be support .net core ?

### ISSUE THREAD

**Issue by xiaoquisme** [fanruinet/Microsoft.Extensions.Identity.Core.zh-Hans#1]

**Comment by fanruinet** [comment]
Yes. This is a resource only assembly and doesn't contain any executable code in it. In fact I'm using it in a .net core mvc application.

**Comment by xiaoquisme** [comment]
Yes ,It works for me .I was wrong using nuget `Microsoft.AspNet.Identity.Core.zh-Hans`

**Comment by fanruinet** [comment]
Sounds great! The nuget package name 'Microsoft.AspNet.Identity.Core.zh-Hans' was reserved by Microsoft so I have to choose a different name.
